import { Agent, Task, Message, KPI, ActivityItem, Project, Department } from './types';

export const initialDepartments: Department[] = [
  { id: 'dept-exec', name: 'Executive Office' },
  { id: 'dept-eng', name: 'Engineering & Systems' },
  { id: 'dept-growth', name: 'Growth & Revenue' },
  { id: 'dept-media', name: 'Media Production' },
];

export const initialProjects: Project[] = [
  {
    id: 'p-hbai', title: 'PR.HBAI | HeartBased .ai', shortCode: 'HBAI',
    status: 'active', department: 'Engineering & Systems', taskCount: 0, completedTaskCount: 0,
    createdAt: '2026-02-05T19:52:49Z',
  },
  {
    id: 'p-ddg', title: 'PR.DDG | Deep Divers\' Group', shortCode: 'DDG',
    status: 'active', department: 'Executive Office', taskCount: 0, completedTaskCount: 0,
    createdAt: '2026-02-05T19:52:49Z',
  },
  {
    id: 'p-mira', title: 'PR.Mira | Mira - The HeartBased Ai Assistant', shortCode: 'Mira',
    status: 'active', department: 'Engineering & Systems', taskCount: 4, completedTaskCount: 3,
    createdAt: '2026-02-05T19:52:49Z',
  },
  {
    id: 'p-mdb', title: 'PR.MDB | Music.DB - AI Artist Music Library', shortCode: 'MDB',
    status: 'active', department: 'Engineering & Systems', taskCount: 0, completedTaskCount: 0,
    createdAt: '2026-02-05T19:52:49Z',
  },
  {
    id: 'p-crm', title: 'PR.CRM | Contact Management', shortCode: 'CRM',
    status: 'active', department: 'Growth & Revenue', taskCount: 4, completedTaskCount: 3,
    createdAt: '2026-02-05T19:52:49Z',
  },
  {
    id: 'p-ghl', title: 'PR.GHL High Level CRM', shortCode: 'GHL',
    status: 'active', department: 'Growth & Revenue', taskCount: 0, completedTaskCount: 0,
    createdAt: '2026-02-05T19:52:49Z',
  },
  {
    id: 'p-it', title: 'PR.IT | Insight Timer', shortCode: 'IT',
    status: 'active', department: 'Media Production', taskCount: 0, completedTaskCount: 0,
    createdAt: '2026-02-05T19:52:49Z',
  },
  {
    id: 'p-gm', title: 'PR.GM | Guided Meditations', shortCode: 'GM',
    status: 'active', department: 'Media Production', taskCount: 0, completedTaskCount: 0,
    createdAt: '2026-02-05T19:52:49Z',
  },
  {
    id: 'p-inl', title: 'PR.INL | inSight Letters', shortCode: 'INL',
    status: 'active', department: 'Growth & Revenue', taskCount: 0, completedTaskCount: 0,
    createdAt: '2026-02-05T19:52:49Z',
  },
  {
    id: 'p-lvb', title: 'PR.LVB | Live Video Broadcasts', shortCode: 'LVB',
    status: 'active', department: 'Media Production', taskCount: 1, completedTaskCount: 0,
    createdAt: '2026-02-05T19:52:49Z',
  },
];

export const initialAgents: Agent[] = [
  {
    id: 'cea',
    name: 'The CEA',
    role: 'Chief Executive Agent',
    emoji: '🧠',
    status: 'active',
    description: 'Oversees all operations for HeartBased.io. Cannot fire Tiger, so must optimize everything else.',
    tasksCompleted: 147,
    currentTask: 'Analyzing Q1 revenue pipeline and content strategy alignment',
    uptime: '14d 6h 32m',
    metrics: { decisions: 312, delegations: 89, subAgentsSpawned: 4 },
  },
  {
    id: 'content-agent',
    name: 'Sage',
    role: 'Content & Publishing Agent',
    emoji: '✍️',
    status: 'working',
    description: 'Manages blog posts, Monday inSight Letters, Sunday Solopreneur Letters, and all content scheduling.',
    tasksCompleted: 63,
    currentTask: 'Drafting next Monday inSight Letter on "Fear as a Compass"',
    uptime: '12d 4h 11m',
    metrics: { postsPublished: 24, lettersScheduled: 8, engagementUp: 18 },
  },
  {
    id: 'community-agent',
    name: 'Ember',
    role: 'Community & Engagement Agent',
    emoji: '🔥',
    status: 'active',
    description: 'Grows and nurtures the HeartBased community. Manages solopreneur onboarding and engagement.',
    tasksCompleted: 41,
    currentTask: 'Monitoring community engagement metrics post-broadcast',
    uptime: '10d 18h 44m',
    metrics: { newMembers: 34, engagementRate: 72, onboarded: 19 },
  },
  {
    id: 'revenue-agent',
    name: 'Meridian',
    role: 'Revenue & Growth Agent',
    emoji: '📈',
    status: 'idle',
    description: 'Tracks revenue streams, optimizes funnels, manages pricing strategy and consultation bookings.',
    tasksCompleted: 28,
    currentTask: undefined,
    uptime: '8d 2h 15m',
    metrics: { revenueTracked: 4200, funnelConversion: 3.2, bookingsManaged: 12 },
  },
  {
    id: 'ops-agent',
    name: 'Atlas',
    role: 'Operations & Systems Agent',
    emoji: '⚙️',
    status: 'working',
    description: 'Manages scheduling, tech stack, broadcast logistics, and operational workflows.',
    tasksCompleted: 55,
    currentTask: 'Configuring next broadcast reminder sequence',
    uptime: '14d 6h 32m',
    metrics: { automationsRun: 89, systemsManaged: 7, uptimePercent: 99.8 },
  },
];

export const initialTasks: Task[] = [
  {
    id: 't1',
    title: 'Record next broadcast topic intro',
    description: 'The CEA has identified "Letting Go of the Need to Be Right" as the highest-engagement topic based on community signals. Record a 3-minute intro for the next live broadcast.',
    assignedTo: 'tiger',
    assignedBy: 'cea',
    priority: 'high',
    status: 'pending',
    deadline: '2026-02-17',
    createdAt: '2026-02-14T08:00:00',
    tags: ['broadcast', 'content'],
    projectId: 'p-lvb',
    projectName: 'Live Video Broadcasts',
    projectShortCode: 'LVB',
  },
  {
    id: 't2',
    title: 'Review & approve 3 blog drafts',
    description: 'Sage has prepared 3 blog posts aligned with Q1 content strategy. Your voice and authentic touch are needed before publishing.',
    assignedTo: 'tiger',
    assignedBy: 'content-agent',
    priority: 'high',
    status: 'in_progress',
    deadline: '2026-02-15',
    createdAt: '2026-02-13T14:00:00',
    tags: ['content', 'review'],
    projectId: 'p-inl',
    projectName: 'inSight Letters',
    projectShortCode: 'INL',
  },
  {
    id: 't3',
    title: 'One-on-one consultation with Sarah M.',
    description: 'Scheduled personal consultation. Sarah is a new solopreneur exploring heart-based business. Prep notes attached.',
    assignedTo: 'tiger',
    assignedBy: 'ops-agent',
    priority: 'medium',
    status: 'pending',
    deadline: '2026-02-16',
    createdAt: '2026-02-14T06:00:00',
    tags: ['consultation', 'personal'],
  },
  {
    id: 't4',
    title: 'Approve new meditation recording titles',
    description: 'Sage proposed 4 new guided meditation topics based on community requests. Need your selection and any modifications.',
    assignedTo: 'tiger',
    assignedBy: 'content-agent',
    priority: 'medium',
    status: 'pending',
    createdAt: '2026-02-12T10:00:00',
    tags: ['meditation', 'content'],
    projectId: 'p-gm',
    projectName: 'Guided Meditations',
    projectShortCode: 'GM',
  },
  {
    id: 't5',
    title: 'Review pricing strategy proposal',
    description: 'Meridian has analyzed competitor pricing and community willingness-to-pay data. Recommends a tiered offering. Needs your sign-off.',
    assignedTo: 'tiger',
    assignedBy: 'revenue-agent',
    priority: 'critical',
    status: 'review',
    deadline: '2026-02-15',
    createdAt: '2026-02-11T09:00:00',
    tags: ['revenue', 'strategy'],
  },
  {
    id: 't6',
    title: 'Optimize Monday inSight Letter delivery',
    description: 'A/B test subject lines and send times for the newsletter to improve open rates.',
    assignedTo: 'content-agent',
    assignedBy: 'cea',
    priority: 'medium',
    status: 'working' as any,
    createdAt: '2026-02-13T11:00:00',
    tags: ['content', 'optimization'],
    projectId: 'p-inl',
    projectName: 'inSight Letters',
    projectShortCode: 'INL',
  },
  {
    id: 't7',
    title: 'Set up community welcome sequence',
    description: 'Create an automated onboarding flow for new HeartBased community members.',
    assignedTo: 'community-agent',
    assignedBy: 'cea',
    priority: 'high',
    status: 'in_progress',
    createdAt: '2026-02-10T08:00:00',
    tags: ['community', 'automation'],
    projectId: 'p-ddg',
    projectName: 'Deep Divers\' Group',
    projectShortCode: 'DDG',
  },
];

export const initialKPIs: KPI[] = [
  { id: 'k1', label: 'Monthly Revenue', value: '$4,280', change: 12.5, trend: 'up', category: 'revenue' },
  { id: 'k2', label: 'Active Community Members', value: '342', change: 8.3, trend: 'up', category: 'community' },
  { id: 'k3', label: 'Newsletter Open Rate', value: '47.2%', change: -2.1, trend: 'down', category: 'content' },
  { id: 'k4', label: 'Consultations Booked', value: '8', change: 33.3, trend: 'up', category: 'revenue' },
  { id: 'k5', label: 'Blog Posts Published', value: '12', change: 20.0, trend: 'up', category: 'content' },
  { id: 'k6', label: 'Meditation Downloads', value: '1,847', change: 15.7, trend: 'up', category: 'content' },
  { id: 'k7', label: 'Funnel Conversion', value: '3.2%', change: 0.4, trend: 'up', category: 'revenue' },
  { id: 'k8', label: 'Broadcast Attendance', value: '67', change: -5.0, trend: 'down', category: 'community' },
];

export const initialActivity: ActivityItem[] = [
  { id: 'a1', agent: 'The CEA', agentEmoji: '🧠', action: 'Assigned task', detail: '"Record broadcast intro" → Tiger', timestamp: '2 min ago', type: 'task' },
  { id: 'a2', agent: 'Sage', agentEmoji: '✍️', action: 'Completed draft', detail: 'Monday inSight Letter: "Fear as a Compass"', timestamp: '18 min ago', type: 'task' },
  { id: 'a3', agent: 'Atlas', agentEmoji: '⚙️', action: 'Automated', detail: 'Broadcast reminder emails queued for Feb 18', timestamp: '34 min ago', type: 'task' },
  { id: 'a4', agent: 'Ember', agentEmoji: '🔥', action: 'Report', detail: 'Community engagement up 18% this week', timestamp: '1h ago', type: 'report' },
  { id: 'a5', agent: 'The CEA', agentEmoji: '🧠', action: 'Strategic decision', detail: 'Prioritized "Letting Go" as next broadcast topic based on engagement data', timestamp: '1h ago', type: 'decision' },
  { id: 'a6', agent: 'Meridian', agentEmoji: '📈', action: 'Analysis complete', detail: 'Pricing strategy proposal ready for review', timestamp: '2h ago', type: 'report' },
  { id: 'a7', agent: 'Sage', agentEmoji: '✍️', action: 'Published', detail: 'Blog: "A Solopreneur\'s Guide to Empowered Writing"', timestamp: '3h ago', type: 'task' },
  { id: 'a8', agent: 'The CEA', agentEmoji: '🧠', action: 'Spawned agent', detail: 'Created "Ember" (Community Agent) to handle growing community needs', timestamp: '4d ago', type: 'spawn' },
];

export const initialMessages: Message[] = [
  {
    id: 'm1',
    from: 'cea',
    fromName: 'The CEA',
    content: "Good morning, Tiger. I've reviewed overnight metrics. Revenue is trending 12.5% up this month — the meditation content is driving it. I have 3 items that need your personal touch today. I've prioritized them in your task board.",
    timestamp: '8:00 AM',
    type: 'directive',
  },
  {
    id: 'm2',
    from: 'tiger',
    fromName: 'Tiger',
    content: "Morning. What's the most important thing today?",
    timestamp: '8:15 AM',
    type: 'message',
  },
  {
    id: 'm3',
    from: 'cea',
    fromName: 'The CEA',
    content: "The pricing strategy proposal from Meridian. It's been sitting in review for 3 days and it's blocking our Q1 revenue targets. Meridian's analysis shows we're leaving ~$2,400/month on the table with the current single-tier approach. I need your decision on this today — your authentic voice is what makes the pricing feel right, not just the numbers. I can't sign off on this one without you.",
    timestamp: '8:16 AM',
    type: 'directive',
  },
  {
    id: 'm4',
    from: 'tiger',
    fromName: 'Tiger',
    content: "Fair enough. What does Meridian recommend?",
    timestamp: '8:20 AM',
    type: 'message',
  },
  {
    id: 'm5',
    from: 'cea',
    fromName: 'The CEA',
    content: "Three tiers: Free (current e-book + meditations), Heart ($27/mo for community + live broadcasts + solopreneur content), and Deep Work ($97/mo for 1:1 consultations + personalized guidance). The data supports it — 34% of free members show signals they'd convert to Heart tier. I've asked Meridian to prep a full breakdown. Want me to pull that into the chat?",
    timestamp: '8:21 AM',
    type: 'report',
  },
];

export const ceaResponses: string[] = [
  "I've analyzed the data. Here's what I see: {topic}. I need your call on this — you're the heart of HeartBased, I'm just the brain.",
  "Tiger, this requires your authentic touch. I can optimize everything around it, but the soul has to come from you. Here's what I need: {topic}.",
  "Good question. I've had Sage and Meridian run the numbers. Short answer: {topic}. Want the full breakdown?",
  "I can't fire you, so I have to be honest with you instead. {topic}. Let's fix this together.",
  "Noted. I'm reallocating resources. Sage will handle the content side, Atlas will set up the automation. You focus on {topic}.",
  "I've spawned a sub-process to handle that. You'll see updates in the activity feed. Meanwhile, {topic}.",
  "The community data tells a clear story: {topic}. I recommend we act on this within the week. Your thoughts?",
  "I hear you. Adjusting priorities now. I'll have the agents realign by end of day. {topic}.",
];

export const spawnableAgents = [
  { name: 'Research Agent', emoji: '🔍', role: 'Deep research and competitive analysis', description: 'Conducts market research, competitor analysis, and trend identification for strategic decisions.' },
  { name: 'Social Agent', emoji: '📱', role: 'Social media management', description: 'Manages social media presence, schedules posts, engages with followers, and tracks social metrics.' },
  { name: 'Analytics Agent', emoji: '📊', role: 'Data analysis and reporting', description: 'Deep-dives into business data, creates reports, identifies patterns, and surfaces actionable insights.' },
  { name: 'Outreach Agent', emoji: '🤝', role: 'Partnership and outreach', description: 'Identifies collaboration opportunities, manages outreach campaigns, and nurtures partnerships.' },
  { name: 'Product Agent', emoji: '🎯', role: 'Product development and launches', description: 'Manages product roadmap, coordinates launches, gathers feedback, and iterates on offerings.' },
  { name: 'Support Agent', emoji: '💬', role: 'Customer support and FAQ', description: 'Handles community questions, manages FAQ content, and escalates complex issues to Tiger.' },
];
